/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from 'react';
import { useAnimations, useGLTF } from '@react-three/drei';

const Horse = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('models/Horse.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions['horse_A_'].play();
  }, [actions]);

  return (
    // <group ref={group} position={[0, -2.5, 0]} scale={[scaleFactor, scaleFactor, scaleFactor]} {...props} dispose={null}>
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Mesh_0">
          <mesh
            name="Mesh_0_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0_1.geometry}
            material={materials['Material.002']}
            morphTargetDictionary={nodes.Mesh_0_1.morphTargetDictionary}
            morphTargetInfluences={nodes.Mesh_0_1.morphTargetInfluences}
          />
          <mesh
            name="Mesh_0_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0_2.geometry}
            material={materials['Material.003']}
            morphTargetDictionary={nodes.Mesh_0_2.morphTargetDictionary}
            morphTargetInfluences={nodes.Mesh_0_2.morphTargetInfluences}
          />
          <mesh
            name="Mesh_0_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0_3.geometry}
            material={materials['Material.004']}
            morphTargetDictionary={nodes.Mesh_0_3.morphTargetDictionary}
            morphTargetInfluences={nodes.Mesh_0_3.morphTargetInfluences}
          />
          <mesh
            name="Mesh_0_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_0_4.geometry}
            material={materials['Material.005']}
            morphTargetDictionary={nodes.Mesh_0_4.morphTargetDictionary}
            morphTargetInfluences={nodes.Mesh_0_4.morphTargetInfluences}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('/models/Horse.glb');

export default Horse;
